### PR TITLE
Switch to Evidence Term

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Comment by henkbirkholz** [comment]
As this PR touches issues #16 and #18, the first question that springs to my mind is:

Is it always Evidence (which from case to case can be very high volume) or also the complementary RATS conceptual message that is the Attestation Result?

**Comment by ounsworth** [comment]
> As this PR touches issues #16 and #18, the first question that springs to my mind is:
> 
> Is it always Evidence (which from case to case can be very high volume) or also the complementary RATS conceptual message that is the Attestation Result?

According to Fig 1, it is the Evidence from the Attester. Interesting idea that the CSR could also carry an Attestation Result. But I'm struggling to imagine how that would work; for example an RA could not replace the Evidence with an Attestation Result without breaking the signature on the CSR.

**Comment by mcr** [comment]
> As this PR touches issues #16 and #18, the first question that springs to my mind is:
> 
> Is it always Evidence (which from case to case can be very high volume) or also the complementary RATS conceptual message that is the Attestation Result?

I can't see how AR could be inserted by the Verifier into the CSR.
If the verifier (operated by the HSM manufacturer, or their representative) needs to communicate things other than pass/fail with the RP (the CA), then they need a different protocol.

**Comment by ounsworth** [comment]
> I can't see how AR could be inserted by the Verifier into the CSR. If the verifier (operated by the HSM manufacturer, or their representative) needs to communicate things other than pass/fail with the RP (the CA), then they need a different protocol.

I think we'll see a lot of explore "Pass/Fail for a given evidence verification profile" (or whatever the right RATS term is for that). Like "Does this CSR indicate compliance with CA/B BRs?", or "I can only issue Windows WiFi certs to fully-patched Windows". Or maybe even, the CA hands the verifier a list of evidence verification profiles (maybe each with its own trust store), and the Verifier hands back a list of profiles that this CSR complies with, the CA then smacks the corresponding OIDs on the cert.

**Comment by mcr** [comment]
> I expect we'll see a lot of "Pass/Fail for a given evidence verification profile" (or whatever the right RATS term is for that). Like "Does this CSR indicate compliance with CA/B BRs?", or "Did this CSR come from TPM-backed CAPI on a fully-patched Windows?". Or maybe even, the CA hands the verifier a list of evidence verification profiles (maybe each with its own trust store), and the Verifier hands back a list of profiles that this CSR complies with, the CA then smacks the corresponding OIDs on the cert.

Sure, but none of those messages can go INTO the CSR. Because it's signed by the Attester, and the Verifier can't modify that.
RATS does not define a protocol between RP and Verifier: we have to pick one or design one.
Your initial proposal that it's a proprietary popen("|hsm-manufacturer-module") is probably a good one for now.

**Comment by ounsworth** [comment]
Note-to-self: Hannes' changes are good. I manually merged from `main` to pick up the other PRs.
Still to do: change the ASN.1 in `CSR-ATTESTATION-2023.ASN` to change "Attestation" to "Evidence".

**Pull request merged**
